# Generated by Django 5.1.4 on 2025-05-06 17:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        error_messages={
                            "invalid": "Please enter a valid phone number with country code (e.g., +254, +256)"
                        },
                        max_length=128,
                        null=True,
                        region="KE",
                        unique=True,
                    ),
                ),
                (
                    "is_first_time",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                (
                    "consent",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(auto_now_add=True)),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Registration"),
                            ("UPDATE", "Details Updated"),
                            ("CONFIRM", "Confirmed Attendance"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.registration",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["service_date"], name="events_serv_service_155cfe_idx"
                    ),
                    models.Index(
                        fields=["attendance_type"],
                        name="events_serv_attenda_513ab2_idx",
                    ),
                ],
                "unique_together": {("member", "service_date")},
            },
        ),
    ]
