# Generated by Django 5.1 on 2024-11-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0003_servicereport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceReport",
        ),
    ]
