# Generated by Django 5.1 on 2024-11-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0004_delete_servicereport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("EXPORT", "Export"),
                    ("VIEW", "View"),
                ],
                max_length=50,
            ),
        ),
    ]
