# Generated by Django 5.1 on 2024-10-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(auto_now_add=True)),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Registration"),
                            ("UPDATE", "Details Updated"),
                            ("CONFIRM", "Confirmed Attendance"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.registration",
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "service_date")},
            },
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
