# Generated by Django 5.1 on 2024-10-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_serviceattendance_delete_attendance"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="serviceattendance",
            index=models.Index(
                fields=["service_date"], name="members_ser_service_15828d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceattendance",
            index=models.Index(
                fields=["attendance_type"], name="members_ser_attenda_22e21a_idx"
            ),
        ),
    ]
