# Generated by Django 5.1 on 2024-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_serviceattendance_members_ser_service_15828d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
