# Generated by Django 5.1 on 2024-11-02 10:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_registration_email_alter_registration_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                error_messages={
                    "invalid": "Please enter a valid phone number with country code (e.g., +254, +256)"
                },
                max_length=128,
                region="KE",
                unique=True,
            ),
        ),
    ]
